name: pro_video_editor_example
description: "Demonstrates how to use the pro_video_editor plugin."
publish_to: 'none'

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  pro_video_editor:
    path: ../

  cupertino_icons: ^1.0.8

  video_player: ^2.9.3
  media_kit: ^1.1.11 # Primary package.
  media_kit_video: ^1.2.5 # For video rendering.
  media_kit_libs_video: ^1.0.5 # Native video dependencies.

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
 
  flutter_lints: ^5.0.0
 

flutter:
  uses-material-design: true
  assets:
    - assets/demo.mp4